Repository JohnSnowLabs/spark-nlp-workshop, pull requests merged in 2022-10, with the labels that each got.

#714 Adding notebook for WordSegmenter Multilingual
  jupyter/annotation/multilingual/WordSegmenterMultilingual.ipynb
Labels: notebooks, Do not merge

#699 Notebook for SpanBertCorefModel
  jupyter/annotation/english/coreference-resolution/Coreference_Resolution_SpanBertCorefModel.ipynb
Labels: notebooks, spark-nlp

#745 Added notebook for new external loadSavedModel
  jupyter/transformers/Import External SavedModel From Remote Storage.ipynb
Labels: enhancement
